---
title: "Assignment 1: Introduction"
author: "Haonan Pei"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.

7.  Initial here to acknowledge that you did not use AI at all in completing this assignment: H.P

## 1) Concept and Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I used R Studio in Stats course of ENV 710 with Betsy. This is the first time I learn how to use R.

2. Are there any components of the course about which you feel confident?

> Answer: I feel like I am pretty good at interpreting data and obeserving specific patterns or trends when conducting data analysis.

3. Are there any components of the course about which you feel apprehensive?

> Answer: I worried about my coding skills and the capability of debugging.

4. Describe a dataset you have used in the past. Explain whether it was a primary or secondary dataset. 

> Answer: In my previous course and limited experience with R, I have used the ranking of happiness level among countries across the world. This is the secondary dataset and the author who developed the ranking already weighted and analyzed data in its own rating structure.

5. Would you describe the day of the month as a nominal, ordinal, interval, or ratio number? Explain your reasoning.

> Answer: I would prefer to describe the day of the month as an ordinal number since the order of days in amonth is strictly from 1 to larger number one by one, which is consistently ranked in sequence.

---

## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 

---https://github.com/Haonan218/EDE_Spring2026

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
